# Generated by Django 5.0 on 2024-03-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='job',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='url.user'),
            preserve_default=False,
        ),
    ]
